source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'activeadmin'
gem 'bitfields'
gem 'mysql2'
gem 'bootstrap-sass', '~> 3.4.1'
gem 'sassc-rails', '>= 2.1.0'
gem 'postmark'
gem 'postmark-rails'
gem 'cancan'
gem 'acts-as-taggable-on'
gem 'active_admin_editor', git: 'https://github.com/ejholmes/active_admin_editor.git'
gem 'devise'
gem 'devise-token_authenticatable'
gem 'jquery-rails'
gem 'dotenv-rails'
gem 'listen'
gem 'bcrypt'
gem 'puma'

gem 'capistrano-bundler'
gem 'capistrano-rails'
gem 'capistrano'
gem 'capistrano3-puma'
gem 'uglifier'

group :development do
  gem 'letter_opener'
end
