source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'activeadmin'
gem 'bitfields'
gem 'mysql2'
gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails'
gem 'postmark'
gem 'postmark-rails'
gem 'cancan'
gem 'acts-as-taggable-on'
gem 'active_admin_editor'
gem 'devise'
gem 'devise-token_authenticatable'
gem 'jquery-rails'
gem 'capistrano'
gem 'dotenv-rails'
gem 'listen'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'coffee-script-source'
  gem 'uglifier'
end
