common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  username: <%= ENV.fetch('DB_USER', 'root') %>
  password: <%= ENV.fetch('DB_PASS', nil) %>
  pool: <%= ENV.fetch('DB_POOL_SIZE', nil) %>

development:
  <<: *common
  database: <%= ENV.fetch('DB_NAME', 'ealagad') %>

test: &test
  <<: *common
  database: <%= ENV.fetch('DB_NAME_TEST', 'ealagad_test') %>

production:
  <<: *common
  database: <%= ENV.fetch('DB_NAME', 'ealagad') %>

staging:
  <<: *common
  database: <%= ENV.fetch('DB_NAME', 'ealagad') %>
